### ISSUE TITLE
Cannont read property 'curve' (and others) of undefined of v3 certificate

### ISSUE THREAD

**Issue by Ruffio** [kjur/jsrsasign#269]
Using version 7.2.2 from bower and looping thru all functions, when I call 'verifySignature', then I get this error on a version 3 certificate:

![image](https://user-images.githubusercontent.com/1877612/27584249-8cc1cc46-5b37-11e7-9f76-f787f78d77f9.png)

Calling 'getExtInfo', I get:
![image](https://user-images.githubusercontent.com/1877612/27585646-66af9532-5b3d-11e7-9f23-70719f80c7ca.png)

Calling 'getExtCRLDistributionPointsURI' I get:
![image](https://user-images.githubusercontent.com/1877612/27585837-144af880-5b3e-11e7-9eff-d3f22c261bcd.png)

Calling 'getInfo' I get:
![image](https://user-images.githubusercontent.com/1877612/27585996-b244cdae-5b3e-11e7-9ee5-fb05b39392ab.png)

Using this certificate:
MIIGYDCCBUigAwIBAgIEU7s4dDANBgkqhkiG9w0BAQsFADBAMQswCQYDVQQGEwJESzESMBAGA1UECgwJVFJVU1QyNDA4MR0wGwYDVQQDDBRUUlVTVDI0MDggT0NFUyBDQSBJSTAeFw0xNTEyMzAxMjE4MDNaFw0xODEyMzAxMjE2NTBaMIGeMQswCQYDVQQGEwJESzEyMDAGA1UECgwpRGFubWFya3MgQXBvdGVrZXJmb3JlbmluZyAvLyBDVlI6MjAxMjQ1MTIxWzAgBgNVBAUTGUNWUjoyMDEyNDUxMi1VSUQ6NjQyOTA2OTgwNwYDVQQDDDBEYW5tYXJrcyBBcG90ZWtlcmZvcmVuaW5nIC0gRGFubWFya3MgQXBvdGVrZXJmb3IwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDQNL1iA9kO241weNpuTm/OoU5i9kOpp+/Vi6OmY14aYEIpgDEWr6nfeGugrsFyR2crOxr7iRhngUykUnSsfSqPkhhGiXdcPtEplSubCzP08zf/0PyIyyV5LoBEZr60M7LmahPuQojb09sKdCTEDMk46LCeISEQGI/ZggALH1SRSQiodctQvVN98okuaJDobgbTi/P2sMu3OK/JSbQrI2kn5d4ShUlWIBkZqsRUBNRmrvfBQzZpv2+mkDMFGouYzSkYccPivzQCx8BV9e2QdrB6KVnT6m/l5ND0d3qY41h0i/CffnjofQmoaQ1a3xO82+A6EF+Dl3QF5WcmfR2Z2C6rAgMBAAGjggMBMIIC/TAOBgNVHQ8BAf8EBAMCA7gwgYkGCCsGAQUFBwEBBH0wezA1BggrBgEFBQcwAYYpaHR0cDovL29jc3AuaWNhMDIudHJ1c3QyNDA4LmNvbS9yZXNwb25kZXIwQgYIKwYBBQUHMAKGNmh0dHA6Ly92LmFpYS5pY2EwMi50cnVzdDI0MDguY29tL29jZXMtaXNzdWluZzAyLWNhLmNlcjCCAUMGA1UdIASCATowggE2MIIBMgYKKoFQgSkBAQEDBDCCASIwLwYIKwYBBQUHAgEWI2h0dHA6Ly93d3cudHJ1c3QyNDA4LmNvbS9yZXBvc2l0b3J5MIHuBggrBgEFBQcCAjCB4TAQFglUUlVTVDI0MDgwAwIBARqBzEZvciBhbnZlbmRlbHNlIGFmIGNlcnRpZmlrYXRldCBn5mxkZXIgT0NFUyB2aWxr5XIsIENQUyBvZyBPQ0VTIENQLCBkZXIga2FuIGhlbnRlcyBmcmEgd3d3LnRydXN0MjQwOC5jb20vcmVwb3NpdG9yeS4gQmVt5nJrLCBhdCBUUlVTVDI0MDggZWZ0ZXIgdmlsa+VyZW5lIGhhciBldCBiZWdy5m5zZXQgYW5zdmFyIGlmdC4gcHJvZmVzc2lvbmVsbGUgcGFydGVyLjAzBgNVHREELDAqgShhcG90ZWtlcmZvcmVuaW5nZW5AYXBvdGVrZXJmb3JlbmluZ2VuLmRrMIGXBgNVHR8EgY8wgYwwLqAsoCqGKGh0dHA6Ly9jcmwuaWNhMDIudHJ1c3QyNDA4LmNvbS9pY2EwMi5jcmwwWqBYoFakVDBSMQswCQYDVQQGEwJESzESMBAGA1UECgwJVFJVU1QyNDA4MR0wGwYDVQQDDBRUUlVTVDI0MDggT0NFUyBDQSBJSTEQMA4GA1UEAwwHQ1JMMzExNzAfBgNVHSMEGDAWgBSZj7oNia4hGkJ6Cq4aTE4i/xDrjDAdBgNVHQ4EFgQUc/W+LbQMXATob80qxnVNE5DeDagwCQYDVR0TBAIwADANBgkqhkiG9w0BAQsFAAOCAQEAWgMjuLxT1GtEfWxR6Giqj2wUZxn0EecPWrWotL5Rvl5kNDXajcnsdAzEBS+0ZCXP1i/to+tupkQOs/o0cO759nBIY0O8ZbOvzsKBeLxWdQp2EuLZKDBwLpN49i8yzSJYWd7/KfH15DcNICvDwHPL6SBjwokCuz5dTFVdjXybOrIihRg8zRKZ4Utm1NV2Rfoh4C9D50uIMgcaIJ2WrhD4uIUbomqy9Ex0qUmTAV6eZh5ynCjlVYie3UqeJ+UoVfpsNMFNRJdoeKsn6g1WU2rgoKzYAzliiC89n3hrNbm7rcBLgDFfWsHUtO1w2PDfRAqJcHWoTQiIQNUCPTa8B9LZ8g==

**Comment by Ruffio** [comment]
@kjur If you want me to test new versions, then just let me know. I have a lot of v3 certificates to test with.
Thumbs up for the good work :-)

**Comment by Ruffio** [comment]
Thanks regarding the instructions for reading the certificate, but I'm already doing it and most is working very nicely :-)

` var newCertificate = certificateData;
        var certificate = new X509();
        certificate.readCertPEM("-----BEGIN CERTIFICATE-----" + certificateData.$raw + "-----END CERTIFICATE-----");     

        for (var key in certificate) {
            var keyString = key.replace("get", "").replace("parse", "").replace("Ext", "").replace(/([A-Z])/g, ' $1').trim();; //Remove get, parse and insert space before capital letters .replace("Ext", "")
            keyString = keyString.replace("A I A Info", "Ext AIA Info").replace("C R L Distribution Points U R I", "Ext CRL Distribution Points URI")
            try {
                if (typeof certificate[key] == "function" && !key.startsWith("read") && key != "getInfo") {
                    var valueString = ParseCertificateEnrichment(key, certificate[key]());
                    if (valueString != "") newCertificate[keyString] = valueString;
                }
            } catch (e) {
                newCertificate[keyString] = "-";
            }
        }

        DisplayCertificate(newCertificate);`

**Comment by kjur** [comment]
I've fixed it in 8.0.1 release today. Thanks.

**Comment by Ruffio** [comment]
Cool, we are getting closer :-)

I still experience the two first issues:
![image](https://user-images.githubusercontent.com/1877612/27772632-b8cb51f8-5f66-11e7-82a6-c0df175f73e8.png)

"Cannot read property 'match' of undefined"
![image](https://user-images.githubusercontent.com/1877612/27772676-61e1d71c-5f67-11e7-8790-ea9aba03fc69.png)

This issue has been closed to early as the issue hasn't been resolved. Please wait for the originator to verify and close the issue.
